### ISSUE TITLE
Homekit设备重置问题

### ISSUE THREAD

**Issue by liantianji** [jedmeng/homebridge-opple#1]
有个问题，假如配置好一个灯，当homebridge启动时，假如电灯被开关关了，先前配置好的灯就在homebridge里消失了，当我再打开灯的开关，重新再打开灯开关时，这时homekit里则认为这个灯是新配件，配置信息是默认的我还得重新调整灯在哪个房间。这样很麻烦。

**Comment by jedmeng** [comment]
遥控灯通过墙壁开关关闭时是断电的，所以没办法搜索到这个灯。这个问题已知，但目前前不好解决，暂时搁置吧。
